# Generated by Django 3.1.4 on 2021-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201211_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Группа, в которой может быть опубликован текст', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Текст публикации', verbose_name='Текст'),
        ),
    ]
