# Generated by Django 2.2.6 on 2021-01-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
